#!/bin/bash

#OPTIONS
JSON commands new

JSON options new
JSON options put "_help" '{
    s:-h,
    l:--help,
    detail:"Muestra la ayuda"
}'


_help() {
    # sconsole -g "init help"
    shelp options commands 
    # shelp options commands
    # exit 0
}


run_commands commands 1
run_options options

_help